dist: xenial
sudo: false
language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - python setup.py install
  - pip install pytest-cov rstcheck
script:
  - pytest --cov-report=xml --cov=gnpy
  - rstcheck --ignore-roles cite --ignore-directives automodule --recursive --ignore-messages '(Duplicate explicit target name.*)' .
  - cd examples; ./transmission_main_example.py
  - cd examples; ./path_requests_run.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
