dist: xenial
os: linux
language: python
services: docker
python:
  - "3.6"
  - "3.7"
  - "3.8"
install: skip
script:
  - pip install --editable .
  - pip install pytest-cov rstcheck
  - pytest --cov-report=xml --cov=gnpy -v
  - rstcheck --ignore-roles cite *.rst
  - sphinx-build -W --keep-going docs/ x-throwaway-location
after_success:
  - bash <(curl -s https://codecov.io/bash)
jobs:
  include:
    - stage: test
      name: Docker image
      script:
        - git fetch --unshallow
        - ./.docker-travis.sh
        - docker images
